[workspace]

members = ["boot", "boot-macros", "examples/test_app"]


resolver = "2" # Recommended for workspaces

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
