[package]
name = "test_app"
version = "0.1.0"
edition = "2021"

publish = false # Examples shouldn't be published

[dependencies]
boot = { path = "../../boot" }                 # Depend on the boot library
tokio = { version = "1", features = ["full"] } # Need tokio for #[tokio::main]
